name: Test & Format & Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  TestFormatLint:
    name: "Test Format Lint"

    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write


    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4

      - uses: actions/cache/restore@v4
        with:
          path: './node_modules'
          key: npm-${{ hashFiles('./package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: 'npm install'

      - run: npm run test && npm run format && npm run lint

      - uses: stefanzweifel/git-auto-commit-action@v5

      - uses: actions/cache/save@v4
        if: always()
        with:
          path: './node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('./package.json') }}

